name: Render Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      REPO_SECRET: ${{ secrets.REPO_SECRET }}

    steps:
      - name: Hello World test
        run: echo "👋 Hello from GitHub Actions!"
        
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: Rscript -e 'install.packages("dplyr")'

      - name: Run script
        run: Rscript your_script.R
