name: Render Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World test
        run: echo "👋 Hello from GitHub Actions!"
